Contenidos/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import aceptar_rechazar_contenido, contenidos, crear_contenido, editar_contenido, eliminar_contenido, enviar_a_revision, publicar_contenido, visualizar_contenido, cargar_subcategorias, eliminar_comentario, visualizar_contenido_aceptado, visualizar_contenido_borrador, visualizar_contenido_revision, ver_historial

urlpatterns = [
    path('contenidos/', contenidos, name='contenidos'),
    path('contenidos/crear/', crear_contenido, name='crear_contenido'),
    path('contenidos/editar/<int:id>/',editar_contenido, name='editar_contenido'),
    path('contenidos/confirmar_eliminacion/<int:pk>/',eliminar_contenido, name='eliminar_contenido'),
    path('contenidos/visualizar/<int:id>/',visualizar_contenido, name='visualizar_contenido'),
    path('ajax/load-subcategorias/', cargar_subcategorias, name='ajax_load_subcategorias'),
    path('comentarios/eliminar/<int:comentario_id>/', eliminar_comentario, name='eliminar_comentario'),
    path('contenidos/borrador/<int:id>/',visualizar_contenido_borrador, name='visualizar_contenido_borrador'),
    path('contenidos/revision/<int:id>/',visualizar_contenido_revision, name='visualizar_contenido_revision'),
    path('contenidos/aceptado/<int:id>/',visualizar_contenido_aceptado, name='visualizar_contenido_aceptado'),
    path('enviar-a-revision/<int:id>/', enviar_a_revision, name='enviar_a_revision'),
    path('aceptar-rechazar-contenido/<int:id>/', aceptar_rechazar_contenido, name='aceptar_rechazar_contenido'),
    path('publicar-contenido/<int:id>/', publicar_contenido, name='publicar_contenido'),
    path('contenidos/historial/<int:id>',ver_historial, name= 'ver_historial')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cms/urls.py
"""
Configuración de URLs para el proyecto CMS.

Este archivo define las rutas a las vistas correspondientes en la aplicación. 
Las vistas se definen en cada módulo correspondiente, y se incluyen tanto vistas basadas en funciones como vistas basadas en clases.

Rutas principales:
- Usuario
- Contenidos
- Categoría
- Plantilla
- Roles
- Permisos
- Tablero Kanban

"""
from django.contrib import admin
from Usuario import views
from django.urls import path, re_path
from django.urls import include




urlpatterns = [

    path('admin/',admin.site.urls),
    path('', views.home, name='home'),  # URL para la página principal
    path('registrar/', views.registrar, name='registrar'),  # URL para el registro
    path('exito/', views.exito, name='exito'),
    path('home/',views.home, name='home'),
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),
    path('Iniciar_Sesion/', views.Iniciar_Sesion, name='Iniciar_Sesion'),
    path('contenidos/', include('Contenidos.urls')),
    path('categoria/', include('Categoria.urls')),
    path('plantilla/', include('Plantilla.urls')),
    path('accounts/', include('allauth.urls')),
    path('roles_listar/', views.roles_listar, name='roles_listar'),
    path('crear_rol/', views.crear_rol, name='crear_rol'),
    path('editar_rol/<int:pk>/', views.editar_rol, name='editar_rol'),
    path('eliminar_rol/<int:pk>/', views.eliminar_rol, name='eliminar_rol'),
    path('ver_usuarios/', views.ver_usuarios, name='ver_usuarios'),
    path('ver_roles/', views.ver_roles, name='ver_roles'),
    path('lista_usuarios/', views.lista_usuarios, name='lista_usuarios'),  # Añade esta línea
    path('eliminar_usuario/<int:pk>/', views.eliminar_usuario, name='eliminar_usuario'),
    path('cambiar_rol_usuario/<int:pk>/', views.cambiar_rol_usuario, name='cambiar_rol_usuario'),
    path('tablero_kanban/', include('TableroKanban.urls')),
    path('reportes/', include('Reportes.urls')),

]

Contenidos/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone
from django.utils.timezone import now
from django.contrib.auth.models import User
from Categoria.models import Categoria, Subcategoria
from Plantilla.models import Plantilla

class Estado(models.Model):
    """
    Modelo que representa un estado de un contenido.
    """
    id = models.AutoField(primary_key=True)  # Identificador único del estado
    """
    Identificador unico del estado.
    """
    descripcion = models.CharField(max_length=50)  # Descripción del estado
    """
    Descripción del estado.
    """
    def __str__(self) -> str:
        """
        Devuelve la representación en cadena del estado.

        Returns:
            str: Descripción del estado.
        """
        return str(self.descripcion)
    

class Contenidos(models.Model):
    """
    Modelo que representa un contenido en el sistema.
    """
    titulo = models.CharField(max_length=255)  # Título del contenido
    """
    (str): El título del contenido.
    """
    contenido = RichTextField(default='')  # Contenido en formato enriquecido
    """
    (RichTextField): El contenido en formato enriquecido.
    """
    fecha_creacion = models.DateTimeField(default=timezone.now, editable=False)  # Fecha de creación
    """
    (DateTimeField): La fecha de creación del contenido.
    """
    fecha_publicacion = models.DateTimeField(null=True, blank=True, editable=False)  # Fecha de publicación
    """
    (DateTimeField): Fecha en la que un contenido fue publicado
    """
    fecha_de_rechazados = models.DateTimeField(null=True, blank=True, editable=False)  # Fecha de rechazo
    """
    (DateTimeField): Fecha en la que un contenido fue rechazado
    """
    fecha_de_inactivacion = models.DateTimeField(null=True, blank=True, editable=False) # Fecha de inactivación
    """
    (DateTimeField): Fecha en la que un contenido fue puesto como inactivo
    """
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)  # Categoría asociada
    """
    (ForeignKey): La categoría asociada al contenido.
    """
    subcategoria = models.ForeignKey(Subcategoria, on_delete=models.SET_NULL, null=True, blank=True)  # Subcategoría asociada
    """
    (ForeignKey): La subcategoría asociada al contenido.
    """
    plantilla = models.ForeignKey(Plantilla, on_delete=models.SET_NULL, null=True, blank=True)  # Plantilla utilizada
    """
    (ForeignKey): La plantilla utilizada para el contenido.
    """
    autor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)  # Autor del contenido
    """
    (ForeignKey): El usuario que creó el contenido.
    """
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)  # Estado del contenido
    """
    (ForeignKey): El estado del contenido.
    """

    numero_lecturas = models.IntegerField(default=0, editable=False)  # Campo para el contador de lecturas
    """
    (IntegerField): Donde se cuenta el numero de visualizaciones de cada contenido
    """

    historial = models.TextField(blank=True, editable=False)
    """
    (TextField): Campo donde se almacena cada accion que se realizo sobre el contenido, desde la creacion hasta todos los estados por los que pasa
    """

    
    def agregar_historial(self, accion, detalles=""):
        """
        Agrega un registro al historial del contenido.
        """
        fecha = now().strftime("%Y-%m-%d %H:%M")
        nuevo_historial = f"{accion} - {detalles} ({fecha})\n"
        self.historial += nuevo_historial
        self.save()

    def __str__(self):
        """
        Devuelve el título del contenido.

        Returns:
            str: Título del contenido.
        """
        return self.titulo

    class Meta:
        """
        Metadatos para el modelo Contenidos.

        Permisos personalizados para la gestión de contenidos:
            can_add: Permiso para agregar contenido.
            can_modify: Permiso para editar contenido.
            can_delete: Permiso para eliminar contenido.
            can_viewInactive: Permiso para ver contenido inactivo.
        """
        permissions = [
            ("can_add", "Puede agregar contenido"),
            ("can_modify", "Puede editar contenido"),
            ("can_delete", "Puede eliminar contenido"),
            ("can_viewInactive", "Puede ver contenido inactivo"),
            ("can_viewBorrador", "Puede ver contenido en borrador"),
            ("can_viewRevision", "Puede ver contenido en revisión"),
            ("can_viewAceptado", "Puede ver contenido aceptado"),
            ("can_change_estado", "Puede cambiar estado"),
            ("can_activateContenido", "Puede activar contenido"),
            ("can_viewReportes", "Puede ver los reportes"),
        ]

class Comentario(models.Model):
    """
    Modelo que representa un comentario sobre un contenido.
    """
    comentario = models.TextField()  # Texto del comentario
    """
    (str): Texto del comentario.
    """
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)  # Relaciona el comentario con el usuario
    """
    (ForeignKey): El usuario que realizó el comentario.
    """
    fecha_creacion = models.DateTimeField(auto_now_add=True)  # Fecha de creación del comentario
    """
    (DateTimeField): Fecha de creación del comentario.
    """
    contenido = models.ForeignKey(Contenidos, related_name='comentarios', on_delete=models.CASCADE)  # Contenido relacionado
    """
    (ForeignKey): Contenido relacionado con el comentario.
    """
    def __str__(self):
        """
        Devuelve una representación en cadena del comentario.

        Returns:
            str: Resumen del comentario que incluye el usuario y la fecha de creación.
        """
        return f'Comentario de {self.usuario} en {self.fecha_creacion}'

Contenidos/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from Categoria.models import Categoria, Subcategoria
from Plantilla.models import Plantilla
from .models import Contenidos, Comentario


class ContenidosForm(forms.ModelForm):
    """
    Formulario para la creación de contenidos. Incluye los campos de
    categoría, subcategoría y plantilla, con opciones dinámicas para 
    subcategorías basadas en la categoría seleccionada.
    """
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.all(),
        widget=forms.Select(attrs={'id': 'categoria-select'}),
        empty_label="Seleccione una categoría",
        label="Categoría"
    )
    subcategoria = forms.ModelChoiceField(
        queryset=Subcategoria.objects.none(),
        widget=forms.Select(attrs={'id': 'subcategoria-select'}),
        empty_label="Seleccione una subcategoría",
        required=False,
        label="Subcategoría"
    )
    plantilla = forms.ModelChoiceField(
        queryset=Plantilla.objects.all(),
        required=False,
        widget=forms.Select,
        empty_label="Seleccione una plantilla",
        label="Plantilla"
    )

    class Meta:
        model = Contenidos
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        """
        Inicializa el formulario. Si hay datos de categoría en los datos enviados,
        se filtran las subcategorías relacionadas, de lo contrario se mantiene 
        el queryset de subcategoría vacío.
        """
        super().__init__(*args, **kwargs)
        if 'categoria' in self.data:
            try:
                categoria_id = int(self.data.get('categoria'))
                self.fields['subcategoria'].queryset = Subcategoria.objects.filter(categoriaPadre_id=categoria_id).order_by('nombre')
            except (ValueError, TypeError):
                self.fields['subcategoria'].queryset = Subcategoria.objects.none()
        else:
            self.fields['subcategoria'].queryset = Subcategoria.objects.none()

    def clean_contenido(self):
        """
        Valida el campo de contenido para asegurarse de que no esté vacío.
        Si está vacío, se lanza una ValidationError.
        """
        contenido = self.cleaned_data.get('contenido')
        if not contenido or contenido.strip() == '':
            raise forms.ValidationError('El campo "contenido" no puede estar vacío.')
        return contenido


class EditarContenidosForm(forms.ModelForm):
    """
    Formulario para la edición de contenidos. Incluye los campos de
    categoría, subcategoría y plantilla, con opciones dinámicas para
    subcategorías basadas en la categoría seleccionada.
    """
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.all(),
        widget=forms.Select(attrs={'id': 'categoria-select'}),
        empty_label="Seleccione una categoría",
        label="Categoría"
    )
    subcategoria = forms.ModelChoiceField(
        queryset=Subcategoria.objects.all(),
        widget=forms.Select(attrs={'id': 'subcategoria-select'}),
        empty_label="Seleccione una subcategoría",
        required=False,
        label="Subcategoría"
    )
    plantilla = forms.ModelChoiceField(
        queryset=Plantilla.objects.all(), 
        required=False,
        widget=forms.Select,
        empty_label="Seleccione una plantilla",
        label="Plantilla"
    )

    class Meta:
        """
        Meta configuración del formulario. Especifica el modelo Contenidos y
        los campos que estarán presentes en el formulario.
        """
        model = Contenidos
        fields = ['titulo', 'contenido', 'categoria', 'subcategoria', 'estado', 'plantilla']

    def __init__(self, *args, **kwargs):
        """
        Inicializa el formulario de edición. Filtra las subcategorías dependiendo
        de la categoría seleccionada, ya sea desde los datos enviados o desde la instancia existente.
        """
        super().__init__(*args, **kwargs)
        if 'categoria' in self.data:
            try:
                categoria_id = int(self.data.get('categoria'))
                self.fields['subcategoria'].queryset = Subcategoria.objects.filter(categoriaPadre_id=categoria_id).order_by('nombre')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk and self.instance.categoria:
            self.fields['subcategoria'].queryset = Subcategoria.objects.filter(categoriaPadre=self.instance.categoria).order_by('nombre')


class VisualizarContenidoForm(forms.ModelForm):
    """
    Formulario para la visualización de contenidos. Se utiliza para mostrar
    los datos sin opción de modificación.
    """
    plantilla = forms.ModelChoiceField(
        queryset=Plantilla.objects.all(), 
        required=False,
        widget=forms.Select,               # Esto asegura que se renderice como un <select>
        empty_label="Seleccione una plantilla",  # Etiqueta para el valor vacío
        label="Plantilla"
    )
    
    class Meta:
        model = Contenidos
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        """
        Inicializa el formulario de visualización. Filtra las subcategorías
        dependiendo de la categoría seleccionada en los datos o instancia actual.
        """
        super().__init__(*args, **kwargs)
        if 'categoria' in self.data:
            try:
                categoria_id = int(self.data.get('categoria'))
                self.fields['subcategoria'].queryset = Subcategoria.objects.filter(categoria_id=categoria_id).order_by('nombre')
            except (ValueError, TypeError):
                pass  # Valor inválido de categoría, ignora y usa el queryset vacío
        elif self.instance.pk:
            self.fields['subcategoria'].queryset = self.instance.categoria.subcategorias.order_by('nombre')


class ComentarioForm(forms.ModelForm):
    """
    Formulario para la creación de comentarios. Solo incluye el campo 'comentario'.
    """
    class Meta:
        """
        Meta configuración del formulario. Especifica el modelo Comentario y
        que solo el campo 'comentario' estará presente en el formulario.
        """
        model = Comentario
        fields = ['comentario']
        widgets = {
            'comentario': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Escribe tu comentario aquí...'}),
        }
        labels = {
            'comentario': '',
        }

Contenidos/templates/contenidos/aceptado.html
{% extends "base_email.html" %}
{% load static %}
{% block titulo %}Cambio de estado de publicación {% endblock %}
{% block contenido %}
    Tu publicación {{ titulo }} ha sido aceptada por el editor y ahora se encuentra en A Publicar.
{% endblock %}

Contenidos/templates/contenidos/aceptado_rev.html
{% extends 'base.html' %} {% block contenido %}
<div class="container">
  <p class="text-uppercase text-muted" style="font-size: 0.8rem">
    {{ contenido.categoria.nombre }}
  </p>

  <h2>{{ contenido.titulo }} (Aceptado)</h2>
  <div
    class="card"
    style="
            margin: {{ contenido.plantilla.margenes.izq }}px {{ contenido.plantilla.margenes.der }}px {{ contenido.plantilla.margenes.aba }}px {{ contenido.plantilla.margenes.arr }}px;
            background-color: {{ contenido.plantilla.colorFondo.codigo }};
        "
  >
    <div class="card-body">
      <div class="contenido">{{ contenido.contenido|safe }}</div>
    </div>
  </div>
  <br />
  <div>
    <!-- Botones de acción -->
    {% if perms.Contenidos.can_activateContenido %}
      <h6 style="color: brown">Desea publicar el contenido?</h6>
    <!-- prettier-ignore -->
    <form action="{% url 'publicar_contenido' contenido.id %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary" name="accion" value="1">Publicar Contenido</button>
      <button type="submit" class="btn btn-primary" name="accion" value="0">Devolver a revisión</button>
      <a class="btn btn-secondary" href="{% url 'contenidos' %}" role="button"
        >Salir</a
      >
    </form>
    {% else %}
      <h6 style="color: brown">Esperando confirmación de un publicador...</h6>
      <a class="btn btn-secondary" href="{% url 'contenidos' %}" role="button"
      >Volver</a
    >
    {% endif %}
  </div>
  <br />
  {% endblock %}
</div>

Contenidos/templates/contenidos/borrador.html
{% extends 'base.html' %}

{% block contenido %}
    <div class="container">
        <p class="text-uppercase text-muted" style="font-size: 0.8rem;">
            {{ contenido.categoria.nombre }}
        </p>

        <h2>{{ contenido.titulo }} (Borrador)</h2>
        <div class="card" style="
            margin: {{ contenido.plantilla.margenes.izq }}px {{ contenido.plantilla.margenes.der }}px {{ contenido.plantilla.margenes.aba }}px {{ contenido.plantilla.margenes.arr }}px;
            background-color: {{ contenido.plantilla.colorFondo.codigo }};
        ">
            <div class="card-body">
                <div class="contenido">
                    {{ contenido.contenido|safe }}
                </div>
            </div>
        </div>
        <br>
        <div>
            <!-- Botones de acción -->
            {% if not perms.Contenidos.can_change_estado and contenido.autor.id == user.id %}
                <form action="{% url 'enviar_a_revision' contenido.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Enviar a Revisión</button>
                    <a class="btn btn-secondary" href="{% url 'contenidos' %}" role="button">Salir</a>
                </form>
            </form>
        {% else %}
            <h6 style="color: brown">Esperando confirmación del autor...</h6>
            <a class="btn btn-secondary" href="{% url 'contenidos' %}" role="button"
              >Volver</a
            >
        {% endif %}
        </div>
        <br>
{% endblock %}

Contenidos/templates/contenidos/borrador_editor.html
{% extends "base_email.html" %}
{% load static %}
{% block titulo %}Cambio de estado de publicación {% endblock %}
{% block contenido %}
    Tu publicación {{ titulo }} ahora se encuentra en borrador.
    
{% endblock %}

Contenidos/templates/contenidos/comentado.html
{% extends "base_email.html" %}
{% load static %}
{% block titulo %} Comentarios en tu publicación {% endblock %}
{% block contenido %}
    Tu publicación {{ titulo }} ha sido comentada.
{% endblock %}

Contenidos/templates/contenidos/contenidos.html
{% extends "base.html" %}

{% block Titulo %} Todos los Contenidos {% endblock %}

{% block contenido %}
<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            {% if perms.Contenidos.add_contenidos %}
            <a class="btn btn-success" href="{% url 'crear_contenido' %}" role="button">Nuevo Contenido</a>
            {% endif %}
        </div>
        <div class="card-body">
            <h4 class="card-title">Filtrar contenidos por:</h4>
            <form method="GET" class="mb-4">
                <div class="row">
                    <div class="col-md-4">
                        <label for="categoria">Categoría:</label>
                        <select name="categoria" id="categoria" class="form-control">
                            <option value="">Todas</option>
                            {% for categoria in categorias %}
                            <option value="{{ categoria.id }}"{% if categoria.id == request.GET.categoria %} selected {% endif %}>{{ categoria.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="subcategoria">Subcategoría:</label>
                        <select name="subcategoria" id="subcategoria" class="form-control">
                            <option value="">Todas</option>
                            {% for subcategoria in subcategorias %}
                            <option value="{{ subcategoria.id }}"{% if subcategoria.id == request.GET.subcategoria %} selected {% endif %}>{{ subcategoria.nombre }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="autor">Autor:</label>
                        <select name="autor" id="autor" class="form-control">
                            <option value="">Todos</option>
                            {% for autor in autores %}
                            <option value="{{ autor.id }}"{% if autor.id == request.GET.autor %} selected {% endif %}>{{ autor.username }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Filtrar</button>
            </form>

            <h4 class="card-title">Todos los contenidos</h4>
            <div class="row">
                {% for contenido in contenidos %}
                {% if contenido.estado.id != 2 or perms.Contenidos.can_viewInactive %}
                {% if contenido.estado.id != 3 or contenido.autor.id == user.id or perms.Contenidos.can_viewBorrador %}
                {% if contenido.estado.id != 4 or contenido.autor.id == user.id or perms.Contenidos.can_viewRevision %}
                {% if contenido.estado.id != 5 or contenido.autor.id == user.id or perms.Contenidos.can_viewAceptado %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100">
                        {% if contenido.imagen %}
                        <img src="{{ contenido.imagen.url }}" class="card-img-top" alt="{{ contenido.titulo }}">
                        {% endif %}
                        <div class="card-body">
                            <!-- Categoría arriba del título -->
                            <p class="card-text text-uppercase text-muted" style="font-size: 0.8rem;">
                                {{ contenido.categoria.nombre }}
                            </p>
                            <!-- Subcategoría debajo -->
                            <p class="card-text text-muted" style="font-size: 0.8rem;">
                                {{ contenido.subcategoria.nombre }}
                            </p>
                            <p class="card-text">
                                {{ contenido.descripcion|truncatewords:20 }}
                            </p>
                            <!-- Título del contenido -->
                            {% if contenido.estado.id == 2 %}
                                <h5 class="card-title" style="color: red;">{{ contenido.titulo }} (inactivo)</h5>
                                <a href="{% url 'visualizar_contenido' contenido.id %}" class="btn btn-primary">Leer más</a>
                            {% elif contenido.estado.id == 3 %}
                                <h5 class="card-title" style="color: brown;">{{ contenido.titulo }} (borrador)</h5>
                                <a href="{% url 'visualizar_contenido_borrador' contenido.id %}" class="btn btn-primary">Leer más</a>
                            {% elif contenido.estado.id == 4 %}
                                <h5 class="card-title" style="color:cadetblue;">{{ contenido.titulo }} (revisión)</h5>
                                <a href="{% url 'visualizar_contenido_revision' contenido.id %}" class="btn btn-primary">Leer más</a>
                            {% elif contenido.estado.id == 5 %}
                                <h5 class="card-title" style="color:rgb(11, 136, 0);">{{ contenido.titulo }} (aceptado)</h5>
                                <a href="{% url 'visualizar_contenido_aceptado' contenido.id %}" class="btn btn-primary">Leer más</a>
                            {% else %}
                                <h5 class="card-title">{{ contenido.titulo }}</h5>
                                <a href="{% url 'visualizar_contenido' contenido.id %}" class="btn btn-primary">Leer más</a>
                            {% endif %}
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Creado por {{ contenido.autor }} el {{ contenido.fecha_creacion }}</small>
                            {% if perms.Contenidos.change_contenidos or perms.Contenidos.delete_contenidos %}
                            <div class="mt-2">
                                {% if perms.Contenidos.change_contenidos or contenido.autor.id == user.id %}
                                    <a class="btn btn-info" href="{% url 'editar_contenido' contenido.id %}" role="button">Editar</a>
                                {% endif %}
                                {% if perms.Contenidos.delete_contenidos %}
                                    <a class="btn btn-danger" href="{% url 'eliminar_contenido' contenido.id %}" role="button">Eliminar</a>
                                {% endif %}
                                <a class="btn btn-secondary" href="{% url 'ver_historial' contenido.id %}" role="button">Ver Historial</a> <!-- Nuevo botón para ver historial -->
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endif %}
                {% endif %}
                {% endif %}
                {% empty %}
                <div class="col-12">
                    <p>No hay contenidos disponibles.</p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

Contenidos/templates/contenidos/crear.html
{% extends "base.html" %}
{% block Titulo %} Agregar contenido {% endblock %}
{% block contenido %}

<div class="card">
    <div class="card-header">Crear un contenido</div>
    <div class="card-body">
        {% include 'contenidos/form.html' %}
    </div>
    <div class="card-footer text-muted"></div>
</div>


{% endblock %}

Contenidos/templates/contenidos/en_revision.html
{% extends "base_email.html" %}
{% load static %}
{% block titulo %}Cambio de estado de publicación {% endblock %}
{% block contenido %}
    Tu publicación {{ titulo }} ahora se encuentra en revisión.
{% endblock %}

Contenidos/templates/contenidos/visualizar.html
{% extends 'base.html' %}

{% block contenido %}
    <div class="container">
        <p class="text-uppercase text-muted" style="font-size: 0.8rem;">
            {{ contenido.categoria.nombre }}
        </p>

        <h2>{{ contenido.titulo }}</h2>
        <div class="card" style="
            margin: {{ contenido.plantilla.margenes.izq }}px {{ contenido.plantilla.margenes.der }}px {{ contenido.plantilla.margenes.aba }}px {{ contenido.plantilla.margenes.arr }}px;
            background-color: {{ contenido.plantilla.colorFondo.codigo }};
        ">
            <div class="card-body">
                <div class="contenido">
                    {{ contenido.contenido|safe }}
                </div>
            </div>
        </div>

        <div class="mt-3">
            <p><strong> POR: {{contenido.autor}}</strong></p>
            <p> {{contenido.fecha_creacion}}</p>
        </div>
        <!-- Sección de comentarios -->
        <div class="comentarios mt-5">
            
            <h4>Comentarios ({{ comentarios.count }})</h4>
            {% for comentario in comentarios %}
                <div class="card mb-3">
                    <div class="card-body">
                        <strong>{{ comentario.usuario.username }}</strong> comentó:
                        <p>{{ comentario.comentario }}</p>
                        <p class="text-muted">{{ comentario.fecha_creacion }}</p>
                        <div class="d-flex justify-content-end">
                            {% if comentario.usuario == request.user or perms.Contenidos.delete_comentario %}
                                <a href="{% url 'eliminar_comentario' comentario.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>No hay comentarios aún. Sé el primero en comentar.</p>
            {% endfor %}
        </div>

        <!-- Formulario para agregar un comentario -->
        <div class="mt-4">
            {% if perms.Contenidos.add_comentario%}
                <h5>Agregar un comentario</h5>
                <form method="post">
                    {% csrf_token %}
                    {{ comentario_form.as_p }}
                    <button type="submit" class="btn btn-primary">Comentar</button>
            {% endif %}
            </form>
        </div>
        
        
{% endblock %}